
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int NUMERO = 43;
  public static final int MAIORQUE = 8;
  public static final int DOIS = 28;
  public static final int NOVE = 35;
  public static final int LPAREN = 14;
  public static final int SEMI = 2;
  public static final int PALAVRA = 42;
  public static final int SEGUNDO = 38;
  public static final int MAIORIGUAL = 11;
  public static final int QUINTO = 41;
  public static final int WRITE = 25;
  public static final int RPAREN = 15;
  public static final int MENORIGUAL = 10;
  public static final int IGUAL = 22;
  public static final int RCOL = 17;
  public static final int PRIMEIRO = 37;
  public static final int VIRG = 18;
  public static final int SEIS = 32;
  public static final int MAIS = 5;
  public static final int IF = 23;
  public static final int UM = 27;
  public static final int ID = 19;
  public static final int QUARTO = 40;
  public static final int EOF = 0;
  public static final int MAIOR = 13;
  public static final int error = 1;
  public static final int MENOS = 4;
  public static final int MENOR = 12;
  public static final int DOBRO = 20;
  public static final int TRES = 29;
  public static final int DEZ = 36;
  public static final int MENORQUE = 9;
  public static final int ATRIB = 3;
  public static final int ELSE = 24;
  public static final int DIVIDIR = 7;
  public static final int OITO = 34;
  public static final int WHILE = 26;
  public static final int LCOL = 16;
  public static final int CINCO = 31;
  public static final int QUATRO = 30;
  public static final int SETE = 33;
  public static final int VEZES = 6;
  public static final int TRIPLO = 21;
  public static final int TERCEIRO = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "ATRIB",
  "MENOS",
  "MAIS",
  "VEZES",
  "DIVIDIR",
  "MAIORQUE",
  "MENORQUE",
  "MENORIGUAL",
  "MAIORIGUAL",
  "MENOR",
  "MAIOR",
  "LPAREN",
  "RPAREN",
  "LCOL",
  "RCOL",
  "VIRG",
  "ID",
  "DOBRO",
  "TRIPLO",
  "IGUAL",
  "IF",
  "ELSE",
  "WRITE",
  "WHILE",
  "UM",
  "DOIS",
  "TRES",
  "QUATRO",
  "CINCO",
  "SEIS",
  "SETE",
  "OITO",
  "NOVE",
  "DEZ",
  "PRIMEIRO",
  "SEGUNDO",
  "TERCEIRO",
  "QUARTO",
  "QUINTO",
  "PALAVRA",
  "NUMERO"
  };
}

